### ISSUE TITLE
State of output pins

### ISSUE THREAD

**Issue by AndrewCarterUK** [PiPHP/GPIO#15]
Creating a new 'output pin' instance rewrites to the sysfs GPIO direction file and resets the pin state.

Solution is to check to see if the pin is already an output pin and only write to the direction file if it isn't.

Tag: @alfredomova

**Comment by gismatthew** [comment]
It seems this project is dead. Does anyone find a good alternative?

**Comment by AndrewCarterUK** [comment]
Sorry - very much looking for maintainers as my time is on other things.

I do maintain a list of resources of similar projects and other PHP programming bits and bobs aimed at the Raspberry Pi: https://github.com/PiPHP/Resources
