### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by kristijansoldo** [PiPHP/GPIO#19]
Hi, 
Does it works on PHP7 ?

**Comment by jrebs** [comment]
kristijan, I haven't had much time to tinker with it yet, but I have installed piphp/gpio on php 7.0.19 last night. Created a simple test script to access a couple of pins and had no issues. At a glance, I don't see anything that would be an issue in 7.0.x.

**Comment by svpernova09** [comment]
I can confirm our tests are passing and the library should work on 7.2, 7.3, and likely 7.4.
