### ISSUE TITLE
php version not declared

### ISSUE THREAD

**Issue by garak** [PiPHP/GPIO#28]
No php version is declared, indeed the whole "require" section is missing from composer.json (didn't look at code, so maybe some other ext could be missing too)

**Comment by svpernova09** [comment]
We don't currently declare a PHP version, I'm brand new to the repo and am currently trying to sort out *which* versions of PHP we should support. Based on default Raspberry Pi OS IMHO we should be supporting 7.2, 7.3, and working to sort out how to get 7.4 installed and ensure working there.

I'm not sure what you were trying to do, but the readme instructions are correct in regards to running `composer require piphp/gpio` to install this into your application.

**Comment by garak** [comment]
What I'm trying to do is improve this repository. Declaring supported php version is a de facto standard (apart from obvious advantages).
IMHO you should support nothing before php 7.2 (7.1 is too old and out of support) and 8.0.
So: `^7.2 || ^8.0`

**Comment by svpernova09** [comment]
> 
> 
> What I'm trying to do is improve this repository. Declaring supported php version is a de facto standard (apart from obvious advantages).
> IMHO you should support nothing before php 7.2 (7.1 is too old and out of support) and 8.0.
> So: `^7.2 || ^8.0`

Ah I see. As it currently stands I believe i"m going to pick 7.3 to standardize on at the moment since 7.4 doesn't come default with Raspberry Pi OS.

**Comment by garak** [comment]
Not supporting current php version is not fair. Moreover, curren Ubuntu for Pi comes with php 7.4

**Comment by svpernova09** [comment]
I'm fairly certain release 0.1.0 will work on PHP 7.4. 

Based on the 1 result in the poll on #26, the only respondent so far is using Raspberry Pi OS

![image](https://user-images.githubusercontent.com/967362/89718057-da052400-d981-11ea-872a-189041b364e3.png)

I don't think it's too far off to get 7.4. Maybe even later today. There's just been several other things I wanted to get updated first.

**Comment by garak** [comment]
Well, you can count me as a late voter for Ubuntu, taking your results to 50/50.
Anyway, you should release 0.1.0 as your *first* release, and targeting 1.0.0 as your stable (everything below 1 is de facto considered unstable)
